version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bacbo_automation
      POSTGRES_PASSWORD: senhaUserNex32

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"  # Porta para a comunicação AMQP
      - "15672:15672"  # Porta para o painel de controle do RabbitMQ (opcional)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

networks:
  default:
    external:
      name: jboss

